### PR TITLE
Verify & CI changes

### LINKED ISSUE #33: [FEAT] Fuzzy matching for self-verification.
# Overview
Users are currently unable to self-verify if they do not type the verification string _exactly_. Fuzzy matching would bring a better user experience with no detriment to moderation or security.

# DoD
* User must be able to verify with phrases similar to but not exactly `I have read and agree to the #welcome-rules`

### LINKED ISSUE #123: [BUG] Verify cog responds to mods in verification channel
**Describe the bug**
The bot will still respond to verified users (eg. mods) in the verification channel, telling them that they have sent the wrong message

**To Reproduce**
1. Be verified
2. Send a message in the verification channel
3. Bot will respond

**Expected behavior**
Bot should not respond to verified users in the verification channel

**Screenshots**
image

### LINKED ISSUE #146: JSON checker CI workflow setup speed
The json checker workflow takes much longer than any of the other workflows to setup the Python environment. This is before installing requirements.
The only differences with this workflow compared to the other workflows is that it uses a newer version of the github action, and it uses Python 3.9.2 as opposed to Python 3.8
Once it has setup the Python environment it is very quick to complete

- Test whether it's py3.9.2 or actions/setup-python@v2 making it slow
- Change the one that makes the most difference in speed, or both if necessary
- Update the other workflows to use actions/setup-python@v2 if it doesn't affect the speed (OPTIONAL)

### LINKED ISSUE #147: Extend .gitignore
Currently the .gitignore file only includes some very basic patterns for Python files. It would be useful to extend this to more Python filetypes, and even include patterns for popular IDEs

### PR DESCRIPTION
**Pull request by issy**
# Initial Checklist
- [x] Has @tigattack / @kdavis / @issy been added as a reviewer?
- [x] If applicable, have the relevant project(s), milestone(s), and label(s) been applied?
- [ ] If applicable, have you added details of the cog to the readme as per [README.md](https://github.com/rHomelab/LabBot-Cogs/blob/develop/README.md#cog-summaries)?

# Details
* Resolves #33
* Resolves #123
* Resolves #146
* Resolves #147

### New Features
* Added `fuzziness` setting to verify cog, which allows for non-strict verification checking
* Moved to event-based verification welcoming, so this cog will still work with a react-based verification system (à la reactrole)
* Sped up json checker CI workflow
* Updated all workflows to actions/setup-python@v2
* Extended .gitignore file with entries for Python, Pycharm, Sublime, Jupyter and VSCode

### Breaking Changes
N/A

### CODE REVIEW

**Comment by issy** [comment]
This still needs testing before converting to a full PR

**Comment by issy** [comment]
This has passed testing

**Comment by issy** [comment]
Currently it will have merge conflicts when #142 is merged. These conflicts should be resolved as much as possible before opening the PR

**Review by tigattack — APPROVED** [review]
Absolute madness, thank you Issy :}

**Comment by issy** [comment]
Merge conflicts have now been resolved, all ready to merge

**Review by tigattack — APPROVED** [review]

**Pull request merged**
