### PR TITLE
#124 Report channel blocklist

### LINKED ISSUE #124: [FEAT] Ability to disable report cog in specific channels
# Overview
## Describe the solution you'd like
Ability the deny usage of `[p]report` and `[p]emergency` in specific channels.

## Is this suggestion based on an existing problem? If so, please describe it

# DoD
* See overview. Suggest functionality similar to the following, but am open to alternatives:
  ```text
  [p]reports channel deny <channel>
  [p]reports channel allow <channel>
  ```

# Stretch
* None.

### PR DESCRIPTION
**Pull request by issy**
# Initial Checklist
- [x] Has @tigattack / @kdavis / @issy been added as a reviewer?
- [x] If applicable, have the relevant project(s), milestone(s), and label(s) been applied?
- [ ] If applicable, have you added details of the cog to the readme as per [README.md](https://github.com/rHomelab/LabBot-Cogs/blob/develop/README.md#cog-summaries)?

# Details
* **Does this resolve an issue?**
Resolves #124

### New Features
* Adds commands to toggle the report/emergency commands in specific channels
  - `[p]emergencies channel <allow|deny> <channel>`
  - `[p]reports channel <allow|deny> <channel>`
* Changed embed format to render timestamps clientside (to account for timezones other than UTC+0)
New embed format

### Breaking Changes
* I hope not

## Additional
N/A

### CODE REVIEW

**Comment by tigattack** [comment]
I think we can probably merge it into one command for the whole cog, rather than splitting out reports and emergencies. I don't see a use case for allowing one but not another.

**Comment by issy** [comment]
You make some good points Mr Tig

**Comment by tigattack** [comment]
Sorry, only just noticed this - Please update report docs in the readme to reflect changes.

**Comment by issy** [comment]
> Sorry, only just noticed this - Please update report docs in the readme to reflect changes.

Done :)

**Review by tigattack — APPROVED** [review]

**Pull request merged**
