### PR TITLE
feat(roleinfo): Added roleinfo cog

### LINKED ISSUE #108: [FEAT] Role information cog
# Overview
A role information cog. I had this idea whilst experiencing the pain of trying to match IDs to roles.

# Commands
```
[p]roleinfo <id>
[p]roleinfo <string>
```

# DoD
* Ability to find role by ID, as per the first command. This should resolve the role's ID to role's name. Output must include, at a minimum, the role's name.

# Stretch
* Ability to find role by name as per the second command. This should resolve the role's name to role's ID. Output must include, at a minimum, the role's ID.
* Include more information, such as:
  * Creation date.
  * Colour.
  * Number of members.
  * Hoist (bool).
  * Mentionable.
  * Position.

### PR DESCRIPTION
**Pull request by issy**
# Initial Checklist
- [x] Has @tigattack / @kdavis / @issy been added as a reviewer?
- [x] If applicable, have the relevant project(s), milestone(s), and label(s) been applied?
- [x] If applicable, have you added details of the cog to the readme as per [README.md](https://github.com/rHomelab/LabBot-Cogs/blob/develop/README.md#cog-summaries)?

# Details
* **Does this resolve an issue?**
Resolves #108

### New Features
* Added a command which allows you to view info on a role by string, mention or ID

image

### Breaking Changes
N/A

## Additional
Two main discussion points:
* Should this command be mods only? (currently all users can use it)
* Role position is currently set with 1 as the role at the top. Should it be 0 indexed instead? Should the order be reversed? (Personally I'm happy with how it is, but open to suggestions)

### CODE REVIEW

**Comment by tigattack** [comment]
> Should this command be mods only? (currently all users can use it)

Perhaps we could allow it for all users but limit them to viewing only the information of any role at or below their highest role?

> Role position is currently set with 1 as the role at the top. Should it be 0 indexed instead? Should the order be reversed? (Personally I'm happy with how it is, but open to suggestions)

Agreed, I think this is fine as-is.

**Comment by tigattack** [comment]
Is this pending changes to resolve CI failure or does it just need to be re-run against the new CI changes?

**Comment by issy** [comment]
> Is this pending changes to resolve CI failure or does it just need to be re-run against the new CI changes?

I've updated this branch with develop so it's been run against the latest CI
it's merge-ready now

**Review by tigattack — APPROVED** [review]
Thanks Issy.

**Pull request merged**
